name: Build and Publish Windows App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and Publish Windows App
      run: npm run deploy:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}